# This file stores the actual values for hello-app, and is monitored by Argo CD.
# Better practice - store this file in a separated GitOps repository

image:
  repository: "412486290165.dkr.ecr.us-east-1.amazonaws.com/ori-repo"
  tag: "9942904"
